# agents/summarizer.py

# Global variable for the text to summarize
TEXT_TO_SUMMARIZE = None  # User must set this before calling agent_main()

def agent_main():
    """
    Summarizer Agent
    ----------------
    Purpose: Summarize the input text by extracting the first sentence or truncating after a certain length.
    
    dspy-inspired Functionality:
    - Demonstrates a multi-step processing approach.
    - Optionally, includes a simple explanation of how the text was summarized.
    
    Usage:
        # In a Python shell:
        from agents import summarizer
        summarizer.TEXT_TO_SUMMARIZE = (
            "FastAPI is a modern, fast (high-performance) web framework for building APIs with Python. "
            "It is based on standard Python type hints and is very easy to use. "
            "This agent summarizes long texts."
        )
        result = summarizer.agent_main()
        print(result)
        # Expected output: { "summary": "FastAPI is a modern, fast web framework for building APIs with Python.", "explanation": "Summary generated by extracting the first sentence." }
    """
    if not TEXT_TO_SUMMARIZE or not isinstance(TEXT_TO_SUMMARIZE, str):
        return {"error": "TEXT_TO_SUMMARIZE is not set or is not a valid string."}
    
    # Step 1: Split the text into sentences
    sentences = TEXT_TO_SUMMARIZE.split('. ')
    
    # Step 2: Choose the first sentence as the summary (or apply more advanced logic if desired)
    summary = sentences[0].strip()
    
    # Append an ellipsis if there is more text
    if len(sentences) > 1:
        summary += "..."
    
    explanation = "Summary generated by extracting the first sentence."
    
    return {
        "summary": summary,
        "explanation": explanation
    }